// <auto-generated />
namespace Data.Migration
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class initialise : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialise));
        
        string IMigrationMetadata.Id
        {
            get { return "201305300645374_initialise"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
